### PR TITLE
(Issue #18) Implement parser function to list available classes

### PR DESCRIPTION
**Pull request by jolshevski**
This is an implementation of the design suggested by @smbambling in issue #18.

I'm not convinced that the node manager module is the best place for this function, but I believe it could enable some compelling design patterns. What do you think @WhatsARanjit? Better suited for another module? Stdlib?

If we end up keeping the function in this module, I'll add an appropriate stanza to the README.

### CODE REVIEW

**Comment by smbambling** [comment]
This looks to just list all classes in an environment. Would one then be expected to parse out the desired classes or dire the function suppor this or should it ?

**Comment by jolshevski** [comment]
Yeah, I see the filtering of returned classes as being outside the responsibility of this function.

**Comment by smbambling** [comment]
Would there be a better method then using the API to get a list of environments on a Puppetserver (master) to loop over.  This is so that one can create both environment groups and classification groups based on a match like 

````
$classes = environment_classes()
$matched = grep($classes, 'role::')
````

**Comment by WhatsARanjit** [comment]
@smbambling @jolshevski The main idea behind this function is to pull a list of classes per environment.  That isn't necessarily tied to management of node_groups.  It might be better suited to put this in stdlib.  If there are use cases for this function outside of node_group management, a user shouldn't have to install this module to get that.

**Comment by jolshevski** [comment]
I agree. 

I'm not certain this will be a common design pattern, so rather than propose an addition to stdlib, I created a module here: https://github.com/jolshevski/puppet-env_utils. We may want to look into merging this into stdlib at some point, but I think this makes sense for now.

Side note for @smbambling - I implemented a function to list all available environments in the new module also. Feel free to contribute feedback, ideas, code, etc, and I'll release to the forge once we're happy with it.

**Pull request closed without merging**
